import { Shift, Booking, Instructor, Client, EmailLog, StudioSettings } from "@/types";

const getTodayString = (offsetDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split("T")[0];
};

export const initialStudioSettings: StudioSettings = {
  studioName: "L'Harmonie Pilates Studio",
  tagline: "Equilibrio, Fuerza y Movimiento Consciente",
  address: "Av. Alvear 1850, Recoleta, Buenos Aires",
  phone: "+54 11 4892-3300",
  instagram: "@lharmonie.pilates",
  cancellationWindowHours: 2,
  allowWaitlist: true,
  currency: "ARS",
};

export const initialInstructors: Instructor[] = [
  {
    id: "inst-1",
    name: "Valentina Rossi",
    email: "valentina@lharmoniepilates.com",
    phone: "+54 9 11 5543-1200",
    specialties: ["reformer", "cadillac", "tower"],
    bio: "Instructora Master certificada en Pilates Clásico y Contemporáneo con 8 años de trayectoria.",
    colorTag: "#4f46e5",
    active: true,
  },
  {
    id: "inst-2",
    name: "Camila Fernández",
    email: "camila@lharmoniepilates.com",
    phone: "+54 9 11 4432-8877",
    specialties: ["mat", "power", "prenatal"],
    bio: "Kinesióloga y especialista en biomecánica postural y Pilates dinámico.",
    colorTag: "#059669",
    active: true,
  },
  {
    id: "inst-3",
    name: "Sofía Benítez",
    email: "sofia@lharmoniepilates.com",
    phone: "+54 9 11 6789-0123",
    specialties: ["reformer", "mat"],
    bio: "Bailarina profesional y formadora en alineación de la columna y flexibilidad funcional.",
    colorTag: "#7c3aed",
    active: true,
  },
  {
    id: "inst-4",
    name: "Julieta Morales",
    email: "julieta@lharmoniepilates.com",
    phone: "+54 9 11 3211-9988",
    specialties: ["cadillac", "power", "tower"],
    bio: "Enfocada en tonificación muscular profunda, fuerza de core y estabilidad neuromuscular.",
    colorTag: "#ea580c",
    active: true,
  },
];

export const initialShifts: Shift[] = [
  {
    id: "shift-101",
    title: "Pilates Reformer Flow",
    discipline: "reformer",
    instructorId: "inst-1",
    instructorName: "Valentina Rossi",
    date: getTodayString(0),
    startTime: "08:00",
    endTime: "09:00",
    capacity: 6,
    bookedCount: 6,
    price: 14000,
    status: "full",
    room: "Studio Reformer - Sala Principal",
    level: "Intermedio",
    description: "Fluidez en cama reformer para trabajar resistencia, equilibrio y tono muscular profundo.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-102",
    title: "Power Reformer & Core",
    discipline: "reformer",
    instructorId: "inst-1",
    instructorName: "Valentina Rossi",
    date: getTodayString(0),
    startTime: "09:30",
    endTime: "10:30",
    capacity: 6,
    bookedCount: 4,
    price: 14000,
    status: "almost_full",
    room: "Studio Reformer - Sala Principal",
    level: "Avanzado",
    description: "Sesión de alta intensidad con resortes pesados y secuencias continuas de core.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-103",
    title: "Mat Pilates & Sculpt",
    discipline: "mat",
    instructorId: "inst-2",
    instructorName: "Camila Fernández",
    date: getTodayString(0),
    startTime: "11:00",
    endTime: "12:00",
    capacity: 10,
    bookedCount: 3,
    price: 10000,
    status: "available",
    room: "Sala Mat & Barre Zen",
    level: "Todos los niveles",
    description: "Trabajo en colchoneta con aros mágicos, pelotas y bandas de resistencia.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-104",
    title: "Cadillac & Tower Strength",
    discipline: "cadillac",
    instructorId: "inst-4",
    instructorName: "Julieta Morales",
    date: getTodayString(0),
    startTime: "16:00",
    endTime: "17:00",
    capacity: 4,
    bookedCount: 1,
    price: 16000,
    status: "available",
    room: "Sala Cadillac Exclusiva",
    level: "Intermedio",
    description: "Trabajo suspendido con barra de empuje y muelles para estiramiento y fuerza sin impacto.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-105",
    title: "Pilates Prenatal & Postura",
    discipline: "prenatal",
    instructorId: "inst-2",
    instructorName: "Camila Fernández",
    date: getTodayString(0),
    startTime: "17:30",
    endTime: "18:30",
    capacity: 8,
    bookedCount: 7,
    price: 12000,
    status: "almost_full",
    room: "Sala Mat & Barre Zen",
    level: "Todos los niveles",
    description: "Movimientos suaves adaptados para futuras mamás, enfocados en suelo pélvico y espalda baja.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-106",
    title: "Reformer Sunset Stretch & Tone",
    discipline: "reformer",
    instructorId: "inst-3",
    instructorName: "Sofía Benítez",
    date: getTodayString(0),
    startTime: "19:00",
    endTime: "20:00",
    capacity: 6,
    bookedCount: 2,
    price: 14000,
    status: "available",
    room: "Studio Reformer - Sala Principal",
    level: "Principiante",
    description: "Cierre de jornada con foco en descompresión vertebral, estiramientos activos y relajación.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-201",
    title: "Morning Reformer Awakening",
    discipline: "reformer",
    instructorId: "inst-3",
    instructorName: "Sofía Benítez",
    date: getTodayString(1),
    startTime: "08:00",
    endTime: "09:00",
    capacity: 6,
    bookedCount: 5,
    price: 14000,
    status: "almost_full",
    room: "Studio Reformer - Sala Principal",
    level: "Todos los niveles",
    description: "Empieza la mañana energizando el cuerpo con secuencias de movilidad articular.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-202",
    title: "Pilates Tower & Reformer Combo",
    discipline: "tower",
    instructorId: "inst-1",
    instructorName: "Valentina Rossi",
    date: getTodayString(1),
    startTime: "10:00",
    endTime: "11:00",
    capacity: 6,
    bookedCount: 0,
    price: 15000,
    status: "available",
    room: "Studio Reformer - Sala Principal",
    level: "Intermedio",
    description: "Combinación de carro deslizante y torre de muelles para un entrenamiento integral.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-203",
    title: "Power Mat HIIT Pilates",
    discipline: "power",
    instructorId: "inst-2",
    instructorName: "Camila Fernández",
    date: getTodayString(1),
    startTime: "18:00",
    endTime: "19:00",
    capacity: 10,
    bookedCount: 10,
    price: 11000,
    status: "full",
    room: "Sala Mat & Barre Zen",
    level: "Avanzado",
    description: "Intervalos de cardio controlado combinados con principios clásicos de contrología.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "shift-301",
    title: "Reformer Precision & Control",
    discipline: "reformer",
    instructorId: "inst-1",
    instructorName: "Valentina Rossi",
    date: getTodayString(2),
    startTime: "09:00",
    endTime: "10:00",
    capacity: 6,
    bookedCount: 1,
    price: 14000,
    status: "available",
    room: "Studio Reformer - Sala Principal",
    level: "Principiante",
    description: "Paso a paso para dominar la técnica de resortes y posturas fundamentales.",
    createdAt: new Date().toISOString(),
  },
];

export const initialBookings: Booking[] = [
  {
    id: "book-001",
    shiftId: "shift-101",
    shiftTitle: "Pilates Reformer Flow",
    shiftDate: getTodayString(0),
    shiftTime: "08:00",
    discipline: "reformer",
    instructorName: "Valentina Rossi",
    room: "Studio Reformer - Sala Principal",
    clientName: "Martina Silveyra",
    clientEmail: "martina.silveyra@gmail.com",
    clientPhone: "+54 9 11 5590-3321",
    cancellationCode: "PIL-M4RT-892",
    status: "confirmed",
    price: 14000,
    notes: "Tiene molestia leve en rodilla izquierda.",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "book-002",
    shiftId: "shift-101",
    shiftTitle: "Pilates Reformer Flow",
    shiftDate: getTodayString(0),
    shiftTime: "08:00",
    discipline: "reformer",
    instructorName: "Valentina Rossi",
    room: "Studio Reformer - Sala Principal",
    clientName: "Lucía Arismendi",
    clientEmail: "lucia.arismendi@hotmail.com",
    clientPhone: "+54 9 11 3344-9911",
    cancellationCode: "PIL-LUC1-774",
    status: "confirmed",
    price: 14000,
    createdAt: new Date(Date.now() - 72000000).toISOString(),
  },
  {
    id: "book-003",
    shiftId: "shift-102",
    shiftTitle: "Power Reformer & Core",
    shiftDate: getTodayString(0),
    shiftTime: "09:30",
    discipline: "reformer",
    instructorName: "Valentina Rossi",
    room: "Studio Reformer - Sala Principal",
    clientName: "Florencia Paz",
    clientEmail: "flor.paz@outlook.com",
    clientPhone: "+54 9 11 8877-6655",
    cancellationCode: "PIL-FLOR-512",
    status: "confirmed",
    price: 14000,
    createdAt: new Date(Date.now() - 40000000).toISOString(),
  },
  {
    id: "book-004",
    shiftId: "shift-103",
    shiftTitle: "Mat Pilates & Sculpt",
    shiftDate: getTodayString(0),
    shiftTime: "11:00",
    discipline: "mat",
    instructorName: "Camila Fernández",
    room: "Sala Mat & Barre Zen",
    clientName: "Paula Gómez",
    clientEmail: "paula.gomez@gmail.com",
    clientPhone: "+54 9 11 6612-4433",
    cancellationCode: "PIL-PAUL-330",
    status: "cancelled",
    cancellationReason: "Imprevisto laboral de último momento",
    cancelledAt: new Date(Date.now() - 10000000).toISOString(),
    price: 10000,
    createdAt: new Date(Date.now() - 50000000).toISOString(),
  },
];

export const initialClients: Client[] = [
  {
    id: "cli-1",
    name: "Martina Silveyra",
    email: "martina.silveyra@gmail.com",
    phone: "+54 9 11 5590-3321",
    totalBookings: 12,
    attendedBookings: 11,
    cancelledBookings: 1,
    lastBookingDate: getTodayString(0),
    healthNotes: "Lesión lumbar en rehabilitación.",
    createdAt: "2026-01-15",
  },
  {
    id: "cli-2",
    name: "Lucía Arismendi",
    email: "lucia.arismendi@hotmail.com",
    phone: "+54 9 11 3344-9911",
    totalBookings: 8,
    attendedBookings: 8,
    cancelledBookings: 0,
    lastBookingDate: getTodayString(0),
    healthNotes: "Ninguna",
    createdAt: "2026-02-01",
  },
  {
    id: "cli-3",
    name: "Florencia Paz",
    email: "flor.paz@outlook.com",
    phone: "+54 9 11 8877-6655",
    totalBookings: 15,
    attendedBookings: 14,
    cancelledBookings: 1,
    lastBookingDate: getTodayString(0),
    createdAt: "2025-11-20",
  },
  {
    id: "cli-4",
    name: "Paula Gómez",
    email: "paula.gomez@gmail.com",
    phone: "+54 9 11 6612-4433",
    totalBookings: 5,
    attendedBookings: 4,
    cancelledBookings: 1,
    lastBookingDate: getTodayString(0),
    createdAt: "2026-03-10",
  },
];

export const initialEmailLogs: EmailLog[] = [
  {
    id: "email-1",
    bookingId: "book-001",
    recipientEmail: "martina.silveyra@gmail.com",
    recipientName: "Martina Silveyra",
    subject: "✨ ¡Tu turno en L'Harmonie Pilates está confirmado!",
    shiftTitle: "Pilates Reformer Flow",
    shiftDate: getTodayString(0),
    shiftTime: "08:00",
    cancellationCode: "PIL-M4RT-892",
    cancellationUrl: `/cancelar/PIL-M4RT-892`,
    sentAt: new Date(Date.now() - 86400000).toISOString(),
    status: "opened",
  },
  {
    id: "email-2",
    bookingId: "book-003",
    recipientEmail: "flor.paz@outlook.com",
    recipientName: "Florencia Paz",
    subject: "✨ ¡Tu turno en L'Harmonie Pilates está confirmado!",
    shiftTitle: "Power Reformer & Core",
    shiftDate: getTodayString(0),
    shiftTime: "09:30",
    cancellationCode: "PIL-FLOR-512",
    cancellationUrl: `/cancelar/PIL-FLOR-512`,
    sentAt: new Date(Date.now() - 40000000).toISOString(),
    status: "sent",
  },
];
